Update README.md
ucsb-cs156-s22/s22-4pm-happycows pull request #11
Opened 2022-05-24 22:01 UTC by KelvinZhang123

# Overview

In a sentence or two, provide an overview of how this pull request updates the main branch.  You may use a bullet list if that helps.

If the new functionality can be expressed as a "User Story" (as a (user of type X) I can (do thing Y) so that (I can acheive goal Z)), then express it that way here.

If it is a refactoring, explain how it improves the code to make it easier to maintain, more efficient, etc.

If it is a bug fix, explain the steps to reproduce the bug in the old code, and how you can tell the bug is gone in the new code.

# Issues Addressed

If this PR closes or deals with issues, mention them and tag the issue number with the `#` syntax.

# Link to Storybook

If there are new React components in this PR, put a link to the relevate Storybook pages from the `-docs-qa` repo here; otherwise delete
this entire heading and section.

# Details

Where applicable, include "before" and "after" screenshots or animated GIFs.   The tool [LiceCAP](https://www.cockos.com/licecap/) or one of [these similar tools](https://www.nextofwindows.com/5-free-tools-to-screen-capture-to-gif-on-windows) 
can be used to capture screenshots/animated GIFs.

# Test Plan (for interactive testing)

Replace this sentence with a step by step list of what actions to take to demonstrate that this PR works successfully.
* If the new functionality can be demonstrated with a list of steps you take starting at the home page of the app, describe those, step by step, including
  what the tester should see at each stage.  (Screenshots help but may be redundant with the screenshots in "details" above).
* If the new functionality can only be demonstrated by using Swagger, explain the steps to take, with screenshots if helpful.
* If the new functionality can only be demonstrated in the Storybook, indicate "Storybook only" under this heading (and be sure the storybook links in the earlier section  work properly.)

## Reminders (delete this section BEFORE asking for staff code review)
- [ ] Be sure that the PR title is clear, and describes what the PR does and why concisely
- [ ] Be sure that the top part of the PR description briefly describes what the PR changes, and why.  Don't just say: "implements issue #37"; say that, but then briefly summarize what changes are made in issue 37, and why those changes are being made.
- [ ] If there is a user story associated with this PR, include the user story 
- [ ] Explicitly link to this pull request each issue that it closes
- [ ] Assign one and ideally two reviewers to review this pull request. 
- [ ] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

2022-05-25 23:11 UTC, charanpreet0 submitted a review, later dismissed

2022-05-26 15:45 UTC, pconrad requested changes
The links are the important part, and you didn't even touch them.

Please consider reading the directions more carefully, and thinking through the purpose here.

2022-05-26 15:45 UTC, pconrad commented on README.md
>  * [Production](https://team04-w22-6pm-3.herokuapp.com/)
Link should be to a working s22 heroku app, not a w22 app.

2022-05-26 15:45 UTC, pconrad commented on README.md
>  * [QA](https://team04-w22-6pm-3-qa.herokuapp.com/)
Link should be to a working s22 qa app, not the w22 one.

2022-05-26 15:45 UTC, pconrad commented on README.md
>  * [Production](https://team04-w22-6pm-4.herokuapp.com/)
Setting up the Heroku repos for the 4pm-4 team isn't your responsibility, necessarily, but if you are going to change the label, then change the links too.  Otherwise, it may be better to leave the 6pm-4 label alone; changing the label and not the links is misleading.

2022-05-26 21:15 UTC, closed without merging