s22-4p-3 cs - Added Leaderboard Header to Commons table, Leaderboard …
ucsb-cs156-s22/s22-4pm-happycows pull request #44
Opened 2022-05-31 07:13 UTC by charanpreet0

…React Component, and Story board

# Overview

In this Pull Request I added the Leaderboard header to the commons table, as well as the Leaderboard Placeholder page which is only accessible when the URL ends in admin/leaderboard/(some number). I need to add the correct connection between the button on the Commons table to the leaderboard page still. I also added the leaderboardFixture.

# Issues Addressed

This addresses the task where need to create a React Component for the Leaderboard as well as the stories

# Details
Before Adding Leaderboard Header
![image](https://user-images.githubusercontent.com/49246453/171111617-5d7cdb36-879d-4fc7-985e-28147a34d0b0.png)
After Adding Leaderboard Header
![image](https://user-images.githubusercontent.com/49246453/171111701-db9de972-4c1e-49ae-8c62-e445ed3d58a6.png)

This below shows the after Image with the URL showing how leaderboard shows up with the Commons ID
![image](https://user-images.githubusercontent.com/49246453/171111386-67ca9b4d-2b0b-4d07-ae17-720eb983e04f.png)

2022-06-01 21:47 UTC, calvitronic approved these changes
Besides the change to package-lock, LGTM. Code is clear and concise complete with testing and the corresponding issue is implemented according to its requirements.

2022-06-02 00:01 UTC, pconrad requested changes
Please remove commented out code.

Also, please add links to new storyboard stories in your PR description.

For example:

Leaderboard table: https://github.com/ucsb-cs156-s22/s22-4pm-happycows/pull/44/files

Also, show before and after screenshots of the changes to CommonsTable, and AppNavbar.

2022-06-02 03:04 UTC, peterbrede approved these changes

2022-06-02 08:58 UTC, calvitronic submitted a review, later dismissed
Comments have been removed, LGTM.

2022-06-02 19:22 UTC, pconrad approved these changes

2022-06-02 19:23 UTC, pconrad approved these changes
LGTM.. will test before merging

2022-06-02 19:24 UTC, kheff16 submitted a review, later dismissed
Can'treview this pr or test in QA, but I would be able to if I had access to Heroku QA and Prod Dashboards. @bzamora020 might be able to QA and test this one for you. Mentors for the team generally have access, and Bryan is yours! Feel free to dismiss this review if Bryan or someone else takes over on it.

2022-06-02 20:09 UTC, calvitronic commented
I just redeployed the branch successfully it is now available to test on the QA.

2022-06-03 08:18 UTC, andrewhlu commented
I'm currently unable to test the app for a few reasons:
1. I'm not listed as an admin within the app
2. Every time I join a commons and I go to its play page, I get errors stating that the UserCommons does not exist

![image](https://user-images.githubusercontent.com/34492835/171816346-4d2348a4-dd46-4543-b726-6336588315ba.png)

If I try to navigate to the user leaderboard page manually, I just get a white screen. Not sure if it's the result of any of the above two issues.

2022-06-03 21:24 UTC, calvitronic approved these changes
Branch updated and tests adjusted to pass all tests, LGTM.

2022-06-04 18:43 UTC, pconrad requested changes
Please fix the singular vs. plural issue.

2022-06-04 18:43 UTC, pconrad commented on frontend/src/fixtures/leaderboardFixtures.js
> +    threeLeaderboard: [
Please fix this.

2022-06-04 20:44 UTC, calvitronic commented on frontend/src/fixtures/leaderboardFixtures.js
> +    threeLeaderboard: [
Done by 62cd1ca9f7bd997a76ddf6e7ed1af143346c3e06

2022-06-04 20:49 UTC, calvitronic commented on frontend/src/main/components/Nav/AppNavbar.js
> +                    <NavDropdown.Item href="/admin/leaderboard">List Leaderboard</NavDropdown.Item>
No longer there from what I can tell.

2022-06-04 20:53 UTC, calvitronic submitted a review, later dismissed
Requested changes implemented, LGTM.

2022-06-04 22:46 UTC, pconrad submitted a review, later dismissed
LGTM.. will test on QA

2022-06-05 00:05 UTC, calvitronic approved these changes

2022-06-05 01:04 UTC, pconrad approved these changes
I see lots of little things that could be improved, but time is short, so I'll assign some of those to the F22 students. :-)

LG(enough)TM

2022-06-05 01:04 UTC, pconrad commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +        },
It's not something that you necessarily need to change, but I'll point out that we probably don't need the commons id in the table, since it will be the same for every single line.

2022-06-05 04:40 UTC, pconrad approved these changes
LGTM

2022-06-05 18:28 UTC, calvitronic approved these changes
Looks good now that leaderboard page is actual placeholder, doesnt rely on backend.

2022-06-05 23:30 UTC, merged