s22-4pm-4: Vr backend degradation rate field added
ucsb-cs156-s22/s22-4pm-happycows pull request #45
Opened 2022-05-31 21:46 UTC by vmreed1

# Overview

I added backend code for a double variable called degradationRate. This variable takes in a decimal value (must be 0 or larger- no negatives). I added code in the controller and entity for this variable. Appears on backend when run on localhosts.  
<img width="1009" alt="Screen Shot 2022-05-27 at 4 01 38 PM" src="https://user-images.githubusercontent.com/56047916/171289728-6fda2cdf-1ea1-4245-a253-9b4e19fe6e02.png">
<img width="721" alt="Screen Shot 2022-05-27 at 4 01 20 PM" src="https://user-images.githubusercontent.com/56047916/171289756-d9caf3ba-64e0-4a40-b96e-79feda7392df.png">
<img width="900" alt="Screen Shot 2022-05-27 at 4 00 01 PM" src="https://user-images.githubusercontent.com/56047916/171289763-b9755c0e-4a7b-46e9-a8e2-b5b7d4e94482.png">
<img width="206" alt="Screen Shot 2022-05-27 at 3 59 47 PM" src="https://user-images.githubusercontent.com/56047916/171289771-a757cffc-aae7-4a6f-ae0e-ebc3bac6ca21.png">

2022-05-31 22:15 UTC, aripo99 submitted a review, later dismissed
LGTM!

2022-06-02 00:11 UTC, pconrad requested changes
There are some commented out lines of code that should be removed.

Otherwise LGTM... once that's done and it's tested on QA, this one looks good to merge.

2022-06-02 00:11 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
> +    //someException.ifPresent((se) -> assertNotNull(se));
We should remove these commented out lines of code.

2022-06-02 00:43 UTC, zoeyz5 commented
LGTM

2022-06-02 04:40 UTC, htn5 approved these changes
LGTM

2022-06-02 04:53 UTC, zoeyz5 approved these changes

2022-06-02 04:54 UTC, zoeyz5 approved these changes
LGTM

2022-06-02 19:11 UTC, kheff16 commented
@vmreed1 looks like there might be a 500 on get /all for this pr. I went back to test on the main deployment to confirm that this is novel, and it is. Here's a screenshot of the dev tools. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26131789/171718890-6604de5e-3fad-41e2-9899-c9b34c9982b6.png">

2022-06-02 21:44 UTC, pconrad approved these changes
LGTM!

2022-06-02 21:44 UTC, merged

2022-10-11 06:56 UTC, WangHaoranRobin commented
Could not replicate. Maybe try "mvn clean"?

On Thu, Jun 2, 2022 at 12:11 PM Kevin Heffernan ***@***.***>
wrote:

> @vmreed1 <https://github.com/vmreed1> looks like there might be a 500 on
> get /all for this pr. I went back to test on the main deployment to confirm
> that this is novel, and it is. Here's a screenshot of the dev tools.
> [image: image]
> <https://user-images.githubusercontent.com/26131789/171718890-6604de5e-3fad-41e2-9899-c9b34c9982b6.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ucsb-cs156-s22/s22-4pm-happycows/pull/45#issuecomment-1145219497>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANLTP6WFW2GY4A7QAKHXGH3VNEBOBANCNFSM5XO5WV5Q>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>