s22-4pm-4: robin degradation rate frontend
ucsb-cs156-s22/s22-4pm-happycows pull request #46
Opened 2022-05-31 22:05 UTC by WangHaoranRobin

Added the frontend fields for degradation in the create, edit, and list commons pages:
![Screen Shot 2022-05-31 at 3 04 59 PM](https://user-images.githubusercontent.com/56047610/171291973-fa30f77d-6f8f-4c9f-9275-ae53b3d63fbc.png)
![Screen Shot 2022-05-31 at 3 05 05 PM](https://user-images.githubusercontent.com/56047610/171291994-cef87f42-b142-4356-a2f1-f53296aba232.png)
![Screen Shot 2022-05-31 at 3 05 07 PM](https://user-images.githubusercontent.com/56047610/171292005-e3db021e-ee5f-42d5-8f06-8d0a25c76210.png)
closes: #16

2022-06-01 01:25 UTC, htn5 reviewed
looks good after testing locally, waiting for stryker to finish

2022-06-01 01:35 UTC, htn5 approved these changes
LGTM

2022-06-02 02:57 UTC, htn5 reviewed
delete commented code in CommonsTable.js, AdminCreateCommonsPage.test.js, and CommonsControllerTest.js @ line 404, 405

2022-06-03 08:49 UTC, andrewhlu submitted a review, later dismissed
Looks like @htn5 had suggested some changes (commented code) but didn't mark it as "requested changes". I'm doing so now so you all are aware of it, please address it! ^^

2022-06-03 21:40 UTC, pconrad requested changes
One small change requested.. otherwise, LGTM!

Will want to test on QA after this change is made.

2022-06-03 21:40 UTC, pconrad commented on frontend/src/main/components/Commons/CommonsForm.js
> +            max: { value: 1, message: "Degradation rate must be less than 100%" },
Matthanjah changed his mind, and instead of this being a number between 0 and 1, we want it to be a percentage, with no fixed maximum.

Should be > 0, and step=0.01 is fine, but remove the test for the max value.

2022-06-03 22:27 UTC, htn5 submitted a review, later dismissed
not sure if it should be >0 like prof conrad said in the previous comment or >=0 like the instructions say, but otherwise, LGTM

2022-06-03 22:28 UTC, WangHaoranRobin commented
> One small change requested.. otherwise, LGTM!
> 
> Will want to test on QA after this change is made.

Deployed on QA!

2022-06-03 22:50 UTC, pconrad approved these changes

2022-06-03 22:52 UTC, pconrad requested changes
Please remove the commented out code (even though it was on the main branch.)

2022-06-03 22:52 UTC, pconrad commented on frontend/src/tests/pages/AdminCreateCommonsPage.test.js
>          // expect(mockNavigate).toBeCalledWith({ "to": "/admin/listcommons" });
Please remove this commented out code.  I know that it was on the main branch, but that's not a reason to not remove it.   When you see a mess, it's good to clean it up.

2022-06-03 23:02 UTC, WangHaoranRobin commented
> Please remove the commented out code (even though it was on the main branch.)

Done!

2022-06-04 04:08 UTC, htn5 approved these changes
lgtm

2022-06-04 23:11 UTC, pconrad approved these changes

2022-06-04 23:12 UTC, pconrad approved these changes
LGTM

2022-06-04 23:30 UTC, merged