s22-4pm-3 kz - New leaderboard button on play page
ucsb-cs156-s22/s22-4pm-happycows pull request #60
Opened 2022-06-02 00:06 UTC by KelvinZhang123

# Overview

Added files are titled as LeaderboardPlayPageButton to avoid confusion with other filed related to the leaderboard. LeaderboardPlayPageButton indicates that the files are related to the leaderboard button on the play page.

Added a new column to the table on the play page titled "Leaderboard" with a new leaderboard png icon as well as a button titled "Board" that the user can click which should direct them to the leaderboard page. 

Currently there is a placeholder link and clicking the button will only direct the user to '../leaderboard/' but once the leaderboard page is created the proper link can be added. On localhost, clicking the button will direct you to 'http://localhost:8080/leaderboard/'.

Attached below is what the new play page looks like on localhost:
<img width="1189" alt="Screen Shot 2022-06-01 at 5 58 01 PM" src="https://user-images.githubusercontent.com/77612269/171525322-d66001e9-383e-42f0-9fad-625481697f28.png">

# Storybook additions
Once merged the component should also appear on storybook and should look like what is displayed below:
<img width="1299" alt="Screen Shot 2022-06-01 at 5 59 46 PM" src="https://user-images.githubusercontent.com/77612269/171525476-d84ae85e-d7c8-40ad-b0b7-83bcd9ab8663.png">

2022-06-02 00:26 UTC, calvitronic approved these changes, later dismissed
This is a very well-executed PR and the changes seem to correctly implement features according to the issue's requirements. No commented out code from what I can see, LGTM!

2022-06-02 00:39 UTC, peterbrede requested changes

2022-06-02 00:39 UTC, peterbrede commented on frontend/src/main/components/Commons/LeaderboardPlayPageButton.js
> +                        <Button variant="outline-danger" data-testid={"leaderboard-playpage-button"}>Board</Button>
remove variant="outline-danger", maybe change name of button to Leaderboard
```suggestion
                        <Button data-testid={"leaderboard-playpage-button"}>Leaderboard</Button>
```

2022-06-02 00:44 UTC, peterbrede approved these changes

2022-06-02 00:48 UTC, peterbrede requested changes

2022-06-02 00:52 UTC, peterbrede approved these changes, later dismissed

2022-06-02 01:18 UTC, calvitronic approved these changes, later dismissed
Good after those new changes, LGTM!

2022-06-03 08:28 UTC, andrewhlu requested changes, later dismissed

2022-06-03 08:28 UTC, andrewhlu commented on frontend/src/main/components/Commons/LeaderboardPlayPageButton.js
> +
is there a reason why there's a set of curly braces here?

2022-06-03 08:28 UTC, andrewhlu commented on frontend/src/main/components/Commons/LeaderboardPlayPageButton.js
> +                            <img alt="Leaderoard Icon" width={100} height ={100} className="icon" src={leaderboardIcon}></img>
a nitpick change to remove a space.

```suggestion
                            <img alt="Leaderoard Icon" width={100} height={100} className="icon" src={leaderboardIcon}></img>
```

2022-06-03 08:28 UTC, andrewhlu commented on frontend/src/tests/components/Commons/LeaderboardPlayPageButton.test.js
> +
I'd suggest also adding some statements to check that, if the button is clicked, we get navigated to the correct page.

2022-06-03 21:45 UTC, calvitronic commented on frontend/src/main/components/Commons/LeaderboardPlayPageButton.js
> +
No need, deleted.

2022-06-03 21:46 UTC, calvitronic commented on frontend/src/tests/components/Commons/LeaderboardPlayPageButton.test.js
> +
Working on this now.

2022-06-03 22:04 UTC, calvitronic commented on frontend/src/tests/components/Commons/LeaderboardPlayPageButton.test.js
> +
Does this do the trick?

2022-06-04 02:36 UTC, KelvinZhang123 reviewed
These changes look great. Thanks Calvin!

2022-06-04 02:47 UTC, calvitronic submitted a review, later dismissed
Updated tests to check if button redirects correctly, updated link to redirect to correct location as well, LGTM.

2022-06-04 18:45 UTC, pconrad approved these changes
LGTM!

2022-06-04 19:18 UTC, pconrad requested changes
I tried deploying this on QA, and ran into some bugs when visiting the play page for a new commons.  This was after resetting the database and redeploying.

Let me encourage you to test on
https://dashboard.heroku.com/apps/s22-4pm-3-happycows-qa with a sequence of
* Create new commons
* Join new commons as admin user
* Visit play page as admin user
* Logout, and login as non-admin user
* Join new commons
* Visit play page as non-admin user


And see if you can get it to be stable.
Let me know when I should take a new look.

2022-06-04 20:16 UTC, calvitronic approved these changes
Seemed to fix unstable behavior by adding optional chaining to commons.id reference.

2022-06-27 21:46 UTC, pconrad commented
Closed; 6pm codebase already has a similar feature.

2022-06-27 21:46 UTC, closed without merging