Update README.md
ucsb-cs156-s22/s22-4pm-happycows pull request #7
Opened 2022-05-24 21:33 UTC by vmreed1

# Overview

Updated README.md with 4pm-4 Heroku link

2022-05-24 21:50 UTC, pconrad requested changes
Check those links... I wonder if they are pointing where you think they are pointing?

2022-05-24 21:50 UTC, pconrad commented on README.md
> +* [QA](https://team04-w22-6pm-4-qa.herokuapp.com/)
Should this link to s22-6pm-3?

2022-05-24 21:50 UTC, pconrad commented on README.md
>  * [QA](https://team04-w22-6pm-4-qa.herokuapp.com/)
w22 or s22?

2022-05-24 21:54 UTC, htn5 commented on README.md
> +* [QA](https://team04-w22-6pm-4-qa.herokuapp.com/)
i believe the production link is correct. the qa link will be fixed in a later readme pull request update

2022-05-24 22:14 UTC, WangHaoranRobin approved these changes
lgtm

2022-05-26 16:18 UTC, pconrad submitted a review, later dismissed

2022-05-26 16:20 UTC, pconrad reviewed
LGTM!

2022-05-26 21:31 UTC, pconrad approved these changes
LGTM

2022-05-26 21:31 UTC, merged

2022-05-26 21:32 UTC, pconrad commented
10 pts because includes OAuth