Update README.md - Added CodeCov
ucsb-cs156-s22/s22-4pm-happycows pull request #8
Opened 2022-05-24 21:46 UTC by charanpreet0

Added CodeCov Badge

2022-05-24 21:47 UTC, pconrad requested changes
`main` not `master`

2022-05-24 21:47 UTC, pconrad commented on README.md
> +[![codecov](https://codecov.io/gh/ucsb-cs156-s22/s22-4pm-happycows/branch/master/graph/badge.svg?token=YedCF0lpyN)](https://codecov.io/gh/ucsb-cs156-s22/s22-4pm-happycows)
Try `main` not `master`

2022-05-25 23:13 UTC, peterbrede approved these changes
Great badge

2022-05-26 16:13 UTC, pconrad approved these changes
LGTM

2022-05-26 21:26 UTC, calvitronic approved these changes
LGTM now that master is changed to main.

2022-05-27 22:38 UTC, merged